FROM golang:1.21.0-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download go.opentelemetry.io/otel
COPY ./*.go ./
RUN go build -trimpath -ldflags="-w -s" -o "dice"

FROM gcr.io/distroless/static-debian11
COPY --from=builder /app/dice /dice
CMD ["/dice"]